
###
POST http://localhost:8080/history HTTP/1.1
content-type: application/json

{
    "userId": "testValue1",
    "workoutId": "testValue2"
}

###
GET http://localhost:8080/history

###
GET http://localhost:8080/history/674118f7d30b235f4328dc4a

###
PUT http://localhost:8080/history/674118f7d30b235f4328dc4a HTTP/1.1
Content-Type: application/json

{
    "userId": "6740f8f63aceb7616f759d50"
}

###
DELETE http://localhost:8080/history/674118f7d30b235f4328dc4a

### Subdocument queries
POST http://localhost:8080/history/674118f7d30b235f4328dc4a/weight HTTP/1.1
Content-Type: application/json

{
    "exerciseName": "Lateral Raises",
    "weight": 15
}
###
GET http://localhost:8080/history/6741221e6e60045992f55299/weight/
###
GET http://localhost:8080/history/674118f7d30b235f4328dc4a/weight/6741221e6e60045992f55299
###
PUT http://localhost:8080/history/674118f7d30b235f4328dc4a/weight/6741221e6e60045992f55299 HTTP/1.1
Content-Type: application/json

{
    "exerciseName": "Cable Pulldown",
    "weight": 60
}
###
DELETE http://localhost:8080/history/674118f7d30b235f4328dc4a/weight/67411b2f73cf9a73e25814a0